import type { MDXComponents } from "mdx/types";
import { MDXRemote } from "next-mdx-remote/rsc";
import remarkGfm from "remark-gfm";
import { getFlowScribeDemoFixture } from "@/lib/flowscribe-demo";

/**
 * Demotes the fixture's own h1/h2/h3 to non-heading-level tags so the sample
 * documentation doesn't compete with the page's real heading hierarchy.
 */
const demoOutputComponents: MDXComponents = {
  h1: (props) => <p className="mt-0 font-display text-body-lg text-mist" {...props} />,
  h2: (props) => <p className="mt-6 font-display text-body text-mist first:mt-0" {...props} />,
  h3: (props) => <p className="mt-4 text-body font-semibold text-mist" {...props} />,
  p: (props) => <p className="mt-3 text-body text-lilac leading-relaxed" {...props} />,
  ul: (props) => <ul className="mt-3 list-disc space-y-1 pl-6 text-body text-lilac" {...props} />,
  ol: (props) => <ol className="mt-3 list-decimal space-y-1 pl-6 text-body text-lilac" {...props} />,
  li: (props) => <li {...props} />,
  strong: (props) => <strong className="font-semibold text-mist" {...props} />,
  a: (props) => (
    <a
      className="text-pulse underline underline-offset-2 hover:text-mist"
      target="_blank"
      rel="noreferrer"
      {...props}
    />
  ),
  code: (props) => (
    <code className="rounded bg-depth px-1.5 py-0.5 font-mono text-mono text-mist" {...props} />
  ),
  pre: (props) => (
    <pre
      className="mt-3 overflow-x-auto rounded-lg bg-depth p-4 font-mono text-mono text-mist"
      {...props}
    />
  ),
  table: (props) => (
    <div className="mt-3 overflow-x-auto rounded-lg border border-conduit">
      <table className="w-full border-collapse text-left text-small" {...props} />
    </div>
  ),
  thead: (props) => <thead className="bg-depth text-mist" {...props} />,
  th: (props) => (
    <th className="border-b border-conduit px-3 py-2 font-mono text-mono" {...props} />
  ),
  td: (props) => <td className="border-b border-conduit px-3 py-2 text-lilac" {...props} />,
};

export function FlowScribeDemo() {
  const { inputJson, outputMarkdown } = getFlowScribeDemoFixture();

  return (
    <section id="demo" className="mt-10 scroll-mt-6">
      <h2 className="font-display text-h3 text-mist">Demo</h2>
      <p className="mt-4 text-body-lg leading-relaxed text-lilac">
        A sample Logic App definition and the documentation FlowScribe generates from it.
      </p>

      <details className="mt-6 rounded-xl border border-conduit bg-surface p-4">
        <summary className="cursor-pointer font-mono text-mono text-mist focus-visible:outline focus-visible:outline-2 focus-visible:outline-pulse">
          Input: Logic App definition (JSON)
        </summary>
        <pre className="mt-4 overflow-x-auto rounded-lg bg-depth p-4 font-mono text-mono text-mist">
          <code>{inputJson}</code>
        </pre>
      </details>

      <div className="mt-6 rounded-xl border border-conduit bg-surface p-6">
        <p className="font-mono text-mono text-muted">Generated by FlowScribe.AI</p>
        <div className="mt-4">
          <MDXRemote
            source={outputMarkdown}
            components={demoOutputComponents}
            options={{ mdxOptions: { remarkPlugins: [remarkGfm] } }}
          />
        </div>
      </div>

      <a
        href="/downloads/flowscribe-sample-documentation.pdf"
        download
        className="mt-6 inline-flex w-fit items-center gap-2 font-mono text-mono text-pulse underline underline-offset-2 hover:text-mist focus-visible:outline focus-visible:outline-2 focus-visible:outline-pulse"
      >
        Download the generated documentation (PDF)
      </a>
    </section>
  );
}
